### PR TITLE
Minor changes to FractalController

### PR DESCRIPTION
**Pull request by mb-afk**
I think there is no need for the createResponse() function.
It would be nice we can add some type hinting in a future pr

### CODE REVIEW

**Comment by bigoper** [comment]
Hey @MohamedBoualleg 

Can you help me with #28 ?

Thanks,
A.I

**Comment by mb-afk** [comment]
Hi @bigoper I'll have a look at it asap

**Comment by bigoper** [comment]
@MohamedBoualleg 
I'll be waiting.
Thanks!

**Comment by bigoper** [comment]
Solved by #29

**Pull request closed without merging**
